//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiGK65CNTT2_65130650.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Thi_65130650Entities : DbContext
    {
        public Thi_65130650Entities()
            : base("name=Thi_65130650Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoaiTinTuc> LoaiTinTucs { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
    
        public virtual int TinTuc_TimKiem(string tieuDe, string tenLTT)
        {
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var tenLTTParameter = tenLTT != null ?
                new ObjectParameter("TenLTT", tenLTT) :
                new ObjectParameter("TenLTT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TinTuc_TimKiem", tieuDeParameter, tenLTTParameter);
        }
    }
}
