//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiGK65CNTT2_65130650.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public string MaTT { get; set; }
        public string TieuDe { get; set; }
        public Nullable<bool> NgonNgu { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string NguoiDang { get; set; }
        public string AnhDaiDien { get; set; }
        public string MaLTT { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LoaiTinTuc LoaiTinTuc { get; set; }
    }
}
